run_frontera_toxigen:
	torchrun --nproc_per_node=4 main.py --config toxigen.json

run_ls6_multi_toxigen:
	torchrun --nproc_per_node=3 main.py --config toxigen.json

run_ls6_toxigen:
	python3 main.py --config toxigen.json