python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-147.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-148.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-149.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-150.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-151.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-152.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-153.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-154.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-155.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-156.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-157.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-158.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-159.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-160.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-161.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-162.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-163.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-164.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-165.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-166.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-167.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-315.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-316.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-317.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-318.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-319.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-320.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-321.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-322.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-323.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-324.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-325.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-326.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-327.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-328.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-329.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-330.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-331.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-332.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-333.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-334.json
python3 main.py ./trial_configurations/toxigen/bart-large-1-new/trial-335.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-147.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-148.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-149.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-150.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-151.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-152.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-153.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-154.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-155.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-156.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-157.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-158.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-159.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-160.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-161.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-162.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-163.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-164.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-165.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-166.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-167.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-315.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-316.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-317.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-318.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-319.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-320.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-321.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-322.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-323.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-324.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-325.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-326.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-327.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-328.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-329.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-330.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-331.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-332.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-333.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-334.json
python3 main.py ./trial_configurations/toxigen/deberta-large-1-new/trial-335.json
